### ISSUE TITLE
pymi 1.0.4 fails to install on Linux and MacOS

### ISSUE THREAD

**Issue by ssbarnea** [cloudbase/PyMI#34]
```
~ $ pip install PyMI                                                                                                                                                                      Collecting PyMI
  Downloading PyMI-1.0.4.zip (2.0MB)
    100% |################################| 2.0MB 626kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dn/bdsfszyj63569bgkwf1jsrw80000gn/T/pip-build-JVxRme/PyMI/setup.py", line 17, in <module>
        version=get_git_version(),
      File "/private/var/folders/dn/bdsfszyj63569bgkwf1jsrw80000gn/T/pip-build-JVxRme/PyMI/setup.py", line 8, in get_git_version
        return g.describe(tags=True)
      File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/git/cmd.py", line 424, in <lambda>
        return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
      File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/git/cmd.py", line 873, in _call_process
        return self.execute(call, **_kwargs)
      File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/git/cmd.py", line 687, in execute
        raise GitCommandError(command, status, stderr_value, stdout_value)
    git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
      cmdline: git describe --tags
      stderr: 'fatal: Not a git repository (or any of the parent directories): .git'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/dn/bdsfszyj63569bgkwf1jsrw80000gn/T/pip-build-JVxRme/PyMI/
```

**Comment by claudiubelu** [comment]
Hi,

PyMI has wheels published on pypi [1], which are used when installing PyMI on Windows hosts. There aren't any wheels for Linux / MacOS, which means that pip will try to download the source and compile itself.

There aren't any Linux /MacOS wheels because they aren't supported OSes at the moment, but may be added in the future.

[1] https://pypi.python.org/pypi/PyMI/1.0.4

**Comment by dirkmueller** [comment]
Sure, but the sources from Pypi (not the wheel) will likely not work on windows either, because it unconditionally assumes the git repository to be present, but that isn't the case in the zip file you're uploading. 

IMHO this is broken, but at least you need to require the dependency on git should you require it (currently there is an import git without having it declared as depencency)

**Comment by ader1990** [comment]
@ssbarnea @dirkmueller the issue has been fixed by recent commits.
